---
- hosts: "{{ host }}"
  tasks:
   - name: Add rhel repository
     import_tasks: RepoRH8.yml
     tags:
      - repo
     when:
      - ansible_facts['distribution_major_version'] == "8"
      - ansible_facts['distribution'] == "RedHat"
   - name: Configure ntp
     import_role:
      name: rhel-system-roles.timesync
