---
- hosts: "{{ host }}"
  tasks:
  - name: Update httpd
    yum:
     name: httpd
     state: latest
    notify: Restart httpd
  - name: Update MySql
    yum:
     name: mysql-server
     state: latest
    notify: Restart mysqld
  - name: Install security Patches
    yum:
     security: yes
     state: latest
  - name: Install bugfix
    yum:
     bugfix: yes
     state: latest

  handlers:
  - name: Restart httpd
    service:
     name: httpd
     state: restarted
  - name: Restart mysqld
    service:
     name: mysqld
     state: restarted
...
